### ISSUE TITLE
#1 초기 프로젝트 구조 설정

### ISSUE THREAD

**Issue by minokim1080** [yanJuicy/jeju-iiin#1]
# Description

초기 프로젝트 구조 커밋

## Todo

- [x] Member Entity 만들기
- [x] Product Entity 만들기
- [x] Cart Entity 만들기
- [x] CartItem Entity 만들기
- [x] Review Entity 만들기
- [x] controller, service, domain, repository 패키지 만들기
- [x] 패키지 별로 커밋용 클래스 1개씩 만들기
